//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MGMTWeb.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AreasSoap", Namespace="http://tempuri.org/")]
    public partial class Areas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AreaCircleOperationCompleted;
        
        private System.Threading.SendOrPostCallback AreasQuareOperationCompleted;
        
        private System.Threading.SendOrPostCallback AreaRectangleOperationCompleted;
        
        private System.Threading.SendOrPostCallback AreaTriangleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Areas() {
            this.Url = global::MGMTWeb.Properties.Settings.Default.MGMTWeb_localhost_Areas;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AreaCircleCompletedEventHandler AreaCircleCompleted;
        
        /// <remarks/>
        public event AreasQuareCompletedEventHandler AreasQuareCompleted;
        
        /// <remarks/>
        public event AreaRectangleCompletedEventHandler AreaRectangleCompleted;
        
        /// <remarks/>
        public event AreaTriangleCompletedEventHandler AreaTriangleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AreaCircle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double AreaCircle(double radius) {
            object[] results = this.Invoke("AreaCircle", new object[] {
                        radius});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void AreaCircleAsync(double radius) {
            this.AreaCircleAsync(radius, null);
        }
        
        /// <remarks/>
        public void AreaCircleAsync(double radius, object userState) {
            if ((this.AreaCircleOperationCompleted == null)) {
                this.AreaCircleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAreaCircleOperationCompleted);
            }
            this.InvokeAsync("AreaCircle", new object[] {
                        radius}, this.AreaCircleOperationCompleted, userState);
        }
        
        private void OnAreaCircleOperationCompleted(object arg) {
            if ((this.AreaCircleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AreaCircleCompleted(this, new AreaCircleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AreasQuare", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AreasQuare(int Length) {
            object[] results = this.Invoke("AreasQuare", new object[] {
                        Length});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AreasQuareAsync(int Length) {
            this.AreasQuareAsync(Length, null);
        }
        
        /// <remarks/>
        public void AreasQuareAsync(int Length, object userState) {
            if ((this.AreasQuareOperationCompleted == null)) {
                this.AreasQuareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAreasQuareOperationCompleted);
            }
            this.InvokeAsync("AreasQuare", new object[] {
                        Length}, this.AreasQuareOperationCompleted, userState);
        }
        
        private void OnAreasQuareOperationCompleted(object arg) {
            if ((this.AreasQuareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AreasQuareCompleted(this, new AreasQuareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AreaRectangle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AreaRectangle(int Width, int Length) {
            object[] results = this.Invoke("AreaRectangle", new object[] {
                        Width,
                        Length});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AreaRectangleAsync(int Width, int Length) {
            this.AreaRectangleAsync(Width, Length, null);
        }
        
        /// <remarks/>
        public void AreaRectangleAsync(int Width, int Length, object userState) {
            if ((this.AreaRectangleOperationCompleted == null)) {
                this.AreaRectangleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAreaRectangleOperationCompleted);
            }
            this.InvokeAsync("AreaRectangle", new object[] {
                        Width,
                        Length}, this.AreaRectangleOperationCompleted, userState);
        }
        
        private void OnAreaRectangleOperationCompleted(object arg) {
            if ((this.AreaRectangleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AreaRectangleCompleted(this, new AreaRectangleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AreaTriangle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AreaTriangle(int height, int baseOfTriangle) {
            object[] results = this.Invoke("AreaTriangle", new object[] {
                        height,
                        baseOfTriangle});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AreaTriangleAsync(int height, int baseOfTriangle) {
            this.AreaTriangleAsync(height, baseOfTriangle, null);
        }
        
        /// <remarks/>
        public void AreaTriangleAsync(int height, int baseOfTriangle, object userState) {
            if ((this.AreaTriangleOperationCompleted == null)) {
                this.AreaTriangleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAreaTriangleOperationCompleted);
            }
            this.InvokeAsync("AreaTriangle", new object[] {
                        height,
                        baseOfTriangle}, this.AreaTriangleOperationCompleted, userState);
        }
        
        private void OnAreaTriangleOperationCompleted(object arg) {
            if ((this.AreaTriangleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AreaTriangleCompleted(this, new AreaTriangleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AreaCircleCompletedEventHandler(object sender, AreaCircleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AreaCircleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AreaCircleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AreasQuareCompletedEventHandler(object sender, AreasQuareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AreasQuareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AreasQuareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AreaRectangleCompletedEventHandler(object sender, AreaRectangleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AreaRectangleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AreaRectangleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AreaTriangleCompletedEventHandler(object sender, AreaTriangleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AreaTriangleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AreaTriangleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591